language: python
git:
  depth: 50
  submodules: true
addons:
  apt:
    packages:
      - build-essential
python:
  - "2.7" # python2 never dies
  - "3.4" # latest version that supports WinXP
  - "3.7" # latest stable
env:
  - TYPE="ext"
  - TYPE="noext"
script:
  - bash run-tests.sh $TYPE
