language: python
git:
  depth: 50
  submodules: true
jobs:
  include:
    - stage: test
        addons:
          apt:
            packages:
              - build-essential
        os: linux
        dist: xenial
        python:
          - "2.7" # python2 never dies
          - "3.4" # latest version that supports WinXP
          - "3.8" # latest stable
        cache: pip
        env:
          - TYPE="ext"
          - TYPE="noext"
        script:
          - bash run-tests.sh $TYPE
    - stage: deploy
      os: linux
      dist: xenial
      script:
        - bash build-waf.sh
      after_script:
        - bash scripts/continious-upload.sh waf-ext waf-noext
