language: python
git:
  depth: 50
  submodules: true
addons:
  apt:
    packages:
      - build-essential
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - TYPE="ext"
  - TYPE="noext"
script:
  - ./run-tests.sh $TYPE
