#! /usr/bin/env python
# encoding: utf-8
# a1batross, 2019

def options(opt):
	opt.add_subproject('subdirs')
	pass

def configure(conf):
	conf.add_subproject('subdirs')
	pass

def build(bld):
	bld.add_subproject('subdirs')
	pass
