#! /usr/bin/env python
# encoding: utf-8
# a1batross, 2019

import sys

TESTS = 'waifuversion subdirs gitversion msdev filter_cflags enforce_pic'

def options(opt):
	opt.add_subproject(TESTS)

def configure(conf):
	conf.add_subproject(TESTS)

def build(bld):
	bld.add_subproject(TESTS)
