#! /usr/bin/env python
# encoding: utf-8
# a1batross, 2019

def options(opt):
	opt.add_option('--foo_test', action='store_true', default=True, dest='foo_test')

def configure(conf):
	conf.env.SUBDIRS_FOO = 'foo'

	# check options() was called
	if not conf.options.foo_test:
		raise Exception('TEST FAILED')

	# check if we really derived environment
	if conf.env.SUBDIRS_ROOT != 'meow':
		raise Exception('TEST FAILED')

def build(bld):
	# check if environment was derived correctly
	if bld.env.SUBDIRS_ROOT != 'meow':
		raise Exception('TEST FAILED')
