#! /usr/bin/env python
# encoding: utf-8
# a1batross, 2019

from waflib import Context

def options(opt):
	pass

def configure(conf):
	conf.msg('Waifu version', Context.WAIFUVERSION)

def build(bld):
	pass
