#! /usr/bin/env python
# encoding: utf-8
# a1batross, 2019

def options(opt):
	opt.load('compiler_c conan')
	pass

def configure(conf):
	conf.load('compiler_c conan')
	# test remote on bincrafters
	conf.add_conan_remote('bincrafters', 'https://api.bintray.com/conan/bincrafters/public-conan');

	# take liblzma and zlib as small example
	conf.add_dependency('lzma/5.2.4@bincrafters/stable') # downloaded from bincrafters
	conf.add_dependency('zlib/1.2.11@conan/stable', uselib_store='custom_uselib')

	# check simple program linked to dependency from Conan
	conf.check_cc(fragment='''#include <stdio.h>
			#include <lzma.h>
			#include <zlib.h>
			int main( void ) { printf( "%d %s", LZMA_VERSION, ZLIB_VERSION ); return 0; }''',
		execute = True,
		msg = "Testing program with dep from Conan",
		use = 'LZMA custom_uselib')

def build(bld):
	pass
